spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pebrisulistiyo/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful
